config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :employees
  resources :companies do
    collection { post :import }
  end

  devise_for :users
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/faq'
  get 'welcome/pricing'
  get 'welcome/feature'
  resources :invoices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :employee
  has_many :purchases
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @search = InvoiceSearch.new(params[:search])
    @invoice = @search.scope
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:date, :company, :tax, :employee_id)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :tax %>
    <%= form.text_field :tax %>
  </div>

  <div class="control-group">
    <%= form.label :salesperson, class: 'control-group' %>
    <div class="controls">
      <%= collection_select( :invoice, :employee_id, Employee.all, :id, :name, {}, {:multiple => false}) %>
    </div>
  </div>

  <!-- <div class="control-group"> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
  <h1>Invoices</h1>
  <div class="pull-right range-query">
    <%= form_tag invoices_path, method: :get do %>
      <%= text_field_tag 'search[date_from]', @search.date_from %>
      <%= text_field_tag 'search[date_to]', @search.date_to %>
      <%= submit_tag 'Search', class: 'btn search-button' %>
    <% end %>
  </div>
</div>

<div class="media">
  <div class = "media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Date</th>
          <th>Company</th>
          <th>Tax</th>
          <th>Salesperson</th>
          <th colspan="3"></th>
        </tr>
      </thead>

    <tbody>
      <% @invoice.each do |invoice| %>
          <tr>
            <td><%= invoice.date.strftime("%Y-%m-%d") %></td>
            <td><%= invoice.company %></td>
            <td><%= invoice.tax %></td>
            <td><%= invoice.employee_id %></td>
            <td><%= link_to 'Show', invoice, class: 'btn btn-mini  btn-primary' %></td>
            <td><%= link_to 'Edit', edit_invoice_path(invoice), class: 'btn btn-mini btn-success' %></td>
            <td><%= link_to 'Destroy', invoice, method: :delete, class: 'btn btn-mini  btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h3> New Invoices </h3>
    <%= link_to 'Create Invoice', new_invoice_path %>
  </div>
</div>
<br>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Company:</strong>
  <%= @invoice.company %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @invoice.tax %>
</p>

<p>
  <strong>Salesperson:</strong>
  <%= @invoice.salesperson %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>