config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :employees
  resources :companies do
    collection { post :import }
  end

  devise_for :users
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/faq'
  get 'welcome/pricing'
  get 'welcome/feature'
  resources :invoices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
end

app/models/company.rb
class Company < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do | row|
      Company.create! row.to_hash
    end
  end
  
  def self.to_csv
    csv.generate do |csv|
    csv << column_names
    all.each do |company|
      csv << company.attributes.values_at(*column_names)
    end
  end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html
      format.csv { redner text: @companies.to_csv }

    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Company.import(params[:file])
    redirect_to companies_path, notice: "Companies added successfully"

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :manager, :status, :terms)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="row"
  <%= form_with(model: company, local: true) do |form| %>
    <% if company.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

        <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="control-group">
      <%= form.label :name, class: 'control-group' %>
      <div class="control">
        <%= form.text_field :name %>
      </div>
    </div>

    <div class="control-group">
      <%= form.label :manager, class: 'control-group' %>
      <div class="control">
        <%= form.text_field :manager %>
      </div>
    </div>

    <div class="control-group">
      <%= form.label :status, class: 'control-group' %>
      <div class="control">
        <%= form.text_field :status %>
      </div>
    </div>

    <div class="control-group">
      <%= form.label :terms , class: 'control-group'%>
      <div class="control">
      <%= form.number_field :terms %>
      </div>
    </div>
    <div class="control">
      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<div class="media">
    <div class = "media-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Manager</th>
            <th>Status</th>
            <th>Terms</th>
            <th colspan="3"></th>
          </tr>
        </thead>


      <tbody>
        <% @companies.each do |company| %>
          <tr>
            <td><%= company.name %></td>
            <td><%= company.manager %></td>
            <td><%= company.status %></td>
            <td><%= company.terms %></td>
            <td><%= link_to 'Show', company %></td>
            <td><%= link_to 'Edit', edit_company_path(company) %></td>
            <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
</div>

<br>

<h3> Import Comanies </h3>
<%= form_tag  import_companies_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Companies" %>
<% end %>

<h3> Download File </h3>
<%= link_to "Report", companies_path(format: "csv"), class: "btn btn-default" %>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @company.manager %>
</p>

<p>
  <strong>Status:</strong>
  <%= @company.status %>
</p>

<p>
  <strong>Terms:</strong>
  <%= @company.terms %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>