config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :employees
  resources :companies do
    collection { post :import }
  end

  devise_for :users
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/faq'
  get 'welcome/pricing'
  get 'welcome/feature'
  resources :invoices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enterpriseape</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

 <div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About us", welcome_about_path %></li>
    <li><%= link_to "Contact", welcome_contact_path %></li>
    <li><%= link_to "Feature", welcome_feature_path %></li>
    <li><%= link_to "FAQs", welcome_faq_path %></li>
    <li><%= link_to "Pricing", welcome_pricing_path %></li>
    <li><%= link_to "Invoice", invoices_path %></li>

    <% if current_user %>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <div class="btn-group pull-right right-nav">
        <button type="button" class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
          <span class="sr-only">Admin</span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Invoices", invoices_path %></li>
          <li><%= link_to "Companies", companies_path %></li>
          <li><%= link_to "Employees", employees_path %></li>
      </div>
    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Sign In", new_user_session_path %></li>

    <% end %>
  </ul>

<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <% flash[:notice] %>
</div>

<% elsif flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <% flash[:error] %>
  </div>

<% elsif flash[:alert] %>
  <div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <% flash[:alert] %>
  </div>
<% end %>


  <%= yield %>
</div>
  </body>
</html>